---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: eso-operator
  name: eso-operator
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets # Namespace where ESO will be installed
  project: default
  source:
    repoURL: https://charts.external-secrets.io # ESO Helm chart repository
    targetRevision: 0.15.0 # Specify the desired version of the Helm chart
    chart: external-secrets # Name of the ESO Helm chart
    helm:
      valuesObject:
        installCRDs: true # Ensures that CRDs are installed with the chart
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: eso-config
  name: eso-config
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-secrets
  project: default
  source:
    path: deploy/external-secrets
    repoURL: https://github.com/sgutierr/secrets-storage-csi-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-crd-manager
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["secrets-store.csi.x-k8s.io"]
  resources: ["secretproviderclasses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["secrets-store.csi.x-k8s.io"]
  resources: ["secretproviderclasspodstatuses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Example ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-crd-binding
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops # Or your actual namespace
roleRef:
  kind: ClusterRole
  name: argocd-crd-manager
  apiGroup: rbac.authorization.k8s.io
