---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: test-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: my-k8s-secret
  data:
    - secretKey: username
      remoteRef:
        key: demo1
        property: key1
    - secretKey: password
      remoteRef:
        key: demo1
        property: key2