---
kind: Secret
apiVersion: v1
metadata:
  name: vault-token
  namespace: test-secrets
data:
  token: cm9vdA==

---  
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: test-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
      path: secret
      server: 'http://hashicorp-vault-server.vault.svc.cluster.local:8200'
      version: v2
      # insecureSkipVerify: true # Disables TLS verification
