apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
  namespace: db-app
spec:
  parameters:
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/team1/db-pass"
        secretKey: "password"
    roleName: database
    vaultAddress: 'http://hashicorp-vault-server.vault.svc.cluster.local:8200'
    vaultSkipTLSVerify: 'true'
  provider: vault