---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-vault-provider
  namespace: test-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider: vault
  parameters:
    roleName: "webapp"
    vaultAddress: "http://hashicorp-vault-server.vault.svc.cluster.local:8200"
    objects: |
      - secretPath: "secret/data/demo1"
        objectName: "demo1-key"
        secretKey: "key1"
      - secretPath: "secret/data/demo2"
        objectName: "demo2-key"
        secretKey: "key1"